spring.application.name=sports-platform-backend
spring.datasource.url=jdbc:postgresql://localhost:5432/sports_db
spring.datasource.username=postgres
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=update
